// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 574fb16d86
// Version Date: 2019年 04月 12日 星期五 00:42:59 UTC

package handlers

import (
	pb "github.com/fanioc/go-poetryminapp/services/mini-app"
)

// Login implements Service.
func Login(CodeLogin string) (*pb.LoginParams, error) {
	request := pb.LoginParams{
		Code: CodeLogin,
	}
	return &request, nil
}

// CheckUserSession implements Service.
func CheckUserSession(SessionCheckUserSession string) (*pb.CheckSessionParams, error) {
	request := pb.CheckSessionParams{
		Session: SessionCheckUserSession,
	}
	return &request, nil
}

// GetUserInfo implements Service.
func GetUserInfo(SessionGetUserInfo string, UserIdGetUserInfo int32) (*pb.GetUserInfoParams, error) {
	request := pb.GetUserInfoParams{
		Session: SessionGetUserInfo,
		UserId:  UserIdGetUserInfo,
	}
	return &request, nil
}

// UpdateUserInfo implements Service.
func UpdateUserInfo(SessionUpdateUserInfo string) (*pb.UpdateUserInfoParams, error) {
	request := pb.UpdateUserInfoParams{
		Session: SessionUpdateUserInfo,
	}
	return &request, nil
}

// GetUserConfig implements Service.
func GetUserConfig(SessionGetUserConfig string, UserIdGetUserConfig int32) (*pb.GetUserConfigParams, error) {
	request := pb.GetUserConfigParams{
		Session: SessionGetUserConfig,
		UserId:  UserIdGetUserConfig,
	}
	return &request, nil
}

// SetUserConfig implements Service.
func SetUserConfig(SessionSetUserConfig string) (*pb.SetUserConfigParams, error) {
	request := pb.SetUserConfigParams{
		Session: SessionSetUserConfig,
	}
	return &request, nil
}
