// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 574fb16d86
// Version Date: 2019年 04月 12日 星期五 00:42:59 UTC

package main

import (
	"flag"

	// This Service
	"github.com/fanioc/go-poetryminapp/services/book/book-service/svc/server"
	"github.com/fanioc/go-poetryminapp/services/book/book-service/svc/server/cli"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(cli.Config)
}
