// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 574fb16d86
// Version Date: 2019年 04月 12日 星期五 00:42:59 UTC

package handlers

import (
	pb "github.com/fanioc/go-poetryminapp/services/book"
)

// GetBookInfo implements Service.
func GetBookInfo(BookIdGetBookInfo int32) (*pb.BookInfoParams, error) {
	request := pb.BookInfoParams{
		BookId: BookIdGetBookInfo,
	}
	return &request, nil
}

// GetBookList implements Service.
func GetBookList(PageGetBookList int32, LimitGetBookList int32) (*pb.BookListParams, error) {
	request := pb.BookListParams{
		Page:  PageGetBookList,
		Limit: LimitGetBookList,
	}
	return &request, nil
}
